import os
import pyautogui
import pandas as pd 
import psutil

def Validacion():
    os.system('C:\QuiterWeb\QuiterWeb.exe')
    pyautogui.countdown(6)
    pyautogui.moveTo(719,559,0)
    pyautogui.click(clicks=1)
    pyautogui.write("Sav1r2023.")
    pyautogui.press("enter")
    pyautogui.countdown(6)
    pyautogui.moveTo(1463,17,0)
    pyautogui.click(clicks=1)
    pyautogui.moveTo(700,452,0.2)
    pyautogui.click(clicks=1)

def bot_semi():
    os.system('C:\QuiterWeb\QuiterWeb.exe')
    pyautogui.countdown(6)
    pyautogui.moveTo(719,559,0)
    pyautogui.click(clicks=1)
    pyautogui.write("Sav1r2023.")
    pyautogui.press("enter")
    pyautogui.countdown(6)
    pyautogui.moveTo(366,107,0)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(51,353,0)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(491,423,0)
    pyautogui.click(clicks=2)
    pyautogui.countdown(6)
    pyautogui.moveTo(1021,518,0)
    pyautogui.click(clicks=1)
    pyautogui.countdown(3)
    pyautogui.moveTo(1321,85,0)
    pyautogui.click(clicks=1)
    pyautogui.countdown(2)
    pyautogui.moveTo(98,210,0)
    pyautogui.click(clicks=2)
    pyautogui.countdown(1)
    pyautogui.moveTo(758,651,0)
    pyautogui.click(clicks=2)
    pyautogui.countdown(1)
    pyautogui.moveTo(769,601,0)
    pyautogui.click(clicks=1)
    pyautogui.moveTo(616,621,0)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(1016,521)
    pyautogui.click(clicks=1)
    pyautogui.moveTo(1016,521)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(78,37)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(1558,37)
    pyautogui.click(clicks=1)
    pyautogui.moveTo(332,47)
    pyautogui.click(clicks=1)
    pyautogui.countdown(1)
    pyautogui.moveTo(1463,17,0)
    pyautogui.click(clicks=1)
    pyautogui.moveTo(700,452,0.2)
    pyautogui.click(clicks=1)

def cerrar_excel_semi():
    pyautogui.countdown(4)
    for prueba in psutil.process_iter():
    #print("check") #Check all the on going process
        if prueba.name() == "EXCEL.EXE":
           prueba.kill()
    print("All EXCEL closed")
